"""Koschei AST'nin güvenli bir alt kümesi için ilk C code generator."""

from __future__ import annotations

from ast_nodes import (
    AssignmentExpression,
    CallExpression,
    Expression,
    ExpressionStatement,
    FunctionDeclaration,
    Identifier,
    LetStatement,
    Literal,
    MemberExpression,
    OrReturnExpression,
    Program,
    ReturnStatement,
    SourceLocation,
)


class CodegenError(Exception):
    def __init__(self, code: str, message: str, location: SourceLocation) -> None:
        self.code = code
        super().__init__(
            f"{code} [satır {location.line}, sütun {location.column}]: {message}"
        )


C_TYPES = {
    "Int": "long long",
    "Float": "double",
    "Bool": "bool",
    "String": "const char *",
    "Void": "void",
}


class CCodeGenerator:
    def __init__(self, program: Program) -> None:
        self.program = program
        self.functions = {item.name: item for item in program.declarations}
        self.locals: dict[str, str] = {}
        self.current_function_name: str | None = None

    def generate(self) -> str:
        header = "\n".join(
            (
                "/* Generated by Koschei v0.1 */",
                "#include <stdbool.h>",
                "#include <stdio.h>",
                "",
            )
        )
        functions = "\n\n".join(
            self._function(item) for item in self.program.declarations
        )
        return f"{header}\n{functions}\n"

    def _function(self, function: FunctionDeclaration) -> str:
        self.locals = {
            parameter.name: str(parameter.type_ref)
            for parameter in function.parameters
        }
        self.current_function_name = function.name
        is_main = function.name == "main"
        return_type = (
            "Int"
            if is_main and function.return_type is None
            else str(function.return_type) if function.return_type else "Void"
        )
        c_return = "int" if is_main else self._c_type(return_type, function.location)
        parameters = ", ".join(
            f"{self._c_type(str(item.type_ref), item.location)} {item.name}"
            for item in function.parameters
        ) or "void"
        lines = [f"{c_return} {function.name}({parameters}) {{"]
        for statement in function.body.statements:
            lines.extend(f"    {line}" for line in self._statement(statement))
        if is_main and not any(
            isinstance(item, ReturnStatement) for item in function.body.statements
        ):
            lines.append("    return 0;")
        lines.append("}")
        return "\n".join(lines)

    def _statement(self, statement: object) -> list[str]:
        if isinstance(statement, LetStatement):
            value_type = self._infer_type(statement.value)
            if value_type is None:
                raise CodegenError(
                    "KS5002",
                    "Değişken tipi C backend tarafından çıkarılamadı.",
                    statement.location,
                )
            self.locals[statement.name] = value_type
            return [
                f"{self._c_type(value_type, statement.location)} {statement.name} = "
                f"{self._expression(statement.value)};"
            ]
        if isinstance(statement, ReturnStatement):
            if statement.value is None:
                return [
                    "return 0;"
                    if self.current_function_name == "main"
                    else "return;"
                ]
            return [f"return {self._expression(statement.value)};"]
        if isinstance(statement, ExpressionStatement):
            expression = statement.expression
            if (
                isinstance(expression, CallExpression)
                and isinstance(expression.callee, Identifier)
                and expression.callee.name in {"print", "println"}
            ):
                return [self._print_call(expression)]
            return [f"{self._expression(expression)};"]
        raise CodegenError(
            "KS5001",
            f"C backend bu statement'i desteklemiyor: {type(statement).__name__}",
            statement.location,
        )

    def _print_call(self, call: CallExpression) -> str:
        if len(call.arguments) != 1:
            raise CodegenError(
                "KS5001",
                "print/println şimdilik tek argüman destekliyor.",
                call.location,
            )
        argument = call.arguments[0]
        type_name = self._infer_type(argument)
        formats = {
            "String": "%s",
            "Int": "%lld",
            "Float": "%g",
            "Bool": "%d",
        }
        if type_name not in formats:
            raise CodegenError(
                "KS5002",
                f"'{type_name}' tipi yazdırılamıyor.",
                call.location,
            )
        suffix = "\\n" if call.callee.name == "println" else ""
        return (
            f'printf("{formats[type_name]}{suffix}", '
            f"{self._expression(argument)});"
        )

    def _expression(self, expression: Expression) -> str:
        if isinstance(expression, Literal):
            if isinstance(expression.value, str):
                return '"' + self._escape_string(expression.value) + '"'
            if isinstance(expression.value, bool):
                return "true" if expression.value else "false"
            return repr(expression.value)
        if isinstance(expression, Identifier):
            return expression.name
        if isinstance(expression, AssignmentExpression):
            return (
                f"{self._expression(expression.target)} = "
                f"{self._expression(expression.value)}"
            )
        if isinstance(expression, CallExpression):
            if (
                isinstance(expression.callee, Identifier)
                and expression.callee.name in {"print", "println"}
            ):
                raise CodegenError(
                    "KS5001",
                    "print çağrısı ifade içinde kullanılamaz.",
                    expression.location,
                )
            arguments = ", ".join(
                self._expression(item) for item in expression.arguments
            )
            return f"{self._expression(expression.callee)}({arguments})"
        if isinstance(expression, (MemberExpression, OrReturnExpression)):
            raise CodegenError(
                "KS5001",
                f"C backend bu ifadeyi henüz desteklemiyor: {type(expression).__name__}",
                expression.location,
            )
        raise CodegenError(
            "KS5001",
            f"Bilinmeyen ifade: {type(expression).__name__}",
            expression.location,
        )

    def _infer_type(self, expression: Expression) -> str | None:
        if isinstance(expression, Literal):
            if isinstance(expression.value, str):
                return "String"
            if isinstance(expression.value, bool):
                return "Bool"
            if isinstance(expression.value, int):
                return "Int"
            if isinstance(expression.value, float):
                return "Float"
        if isinstance(expression, Identifier):
            return self.locals.get(expression.name)
        if isinstance(expression, AssignmentExpression):
            return self._infer_type(expression.value)
        if isinstance(expression, CallExpression) and isinstance(
            expression.callee, Identifier
        ):
            function = self.functions.get(expression.callee.name)
            if function:
                return str(function.return_type) if function.return_type else "Void"
        return None

    @staticmethod
    def _escape_string(value: str) -> str:
        return (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
        )

    @staticmethod
    def _c_type(type_name: str, location: SourceLocation) -> str:
        c_type = C_TYPES.get(type_name)
        if c_type is None:
            raise CodegenError(
                "KS5002",
                f"'{type_name}' tipi ilk C backend tarafından desteklenmiyor.",
                location,
            )
        return c_type


def generate_c(program: Program) -> str:
    return CCodeGenerator(program).generate()
