"""Koschei AST'nin güvenli alt kümesi için C code generator."""

from __future__ import annotations

import re

from ast_nodes import (
    AssignmentExpression,
    BinaryExpression,
    Block,
    CallExpression,
    Expression,
    ExpressionStatement,
    FunctionDeclaration,
    Identifier,
    IfStatement,
    LetStatement,
    Literal,
    MatchStatement,
    MemberExpression,
    OrReturnExpression,
    Program,
    ReturnStatement,
    SourceLocation,
    UnaryExpression,
    WhileStatement,
)


class CodegenError(Exception):
    def __init__(self, code: str, message: str, location: SourceLocation) -> None:
        self.code = code
        super().__init__(
            f"{code} [satır {location.line}, sütun {location.column}]: {message}"
        )


C_TYPES = {
    "Int": "long long",
    "Float": "double",
    "Bool": "bool",
    "String": "const char *",
    "Error": "const char *",
    "Void": "void",
}


class CCodeGenerator:
    def __init__(self, program: Program) -> None:
        self.program = program
        self.functions = {item.name: item for item in program.declarations}
        self.local_scopes: list[dict[str, str]] = []
        self.current_function_name: str | None = None
        self.current_return_type: str | None = None
        self.safe_type_definitions: dict[str, str] = {}
        self.temp_counter = 0

    def generate(self) -> str:
        prototypes = "\n".join(
            self._prototype(item) + ";" for item in self.program.declarations
        )
        functions = "\n\n".join(
            self._function(item) for item in self.program.declarations
        )
        runtime_types = "\n\n".join(self.safe_type_definitions.values())
        header = "\n".join(
            (
                "/* Generated by Koschei v0.4 */",
                "#include <stdbool.h>",
                "#include <stdio.h>",
                "",
            )
        )
        sections = [header]
        if runtime_types:
            sections.append(runtime_types)
        sections.extend((prototypes, functions))
        return "\n\n".join(section for section in sections if section) + "\n"

    def _prototype(self, function: FunctionDeclaration) -> str:
        is_main = function.name == "main"
        return_type = (
            "Int"
            if is_main and function.return_type is None
            else str(function.return_type) if function.return_type else "Void"
        )
        c_return = "int" if is_main else self._c_type(return_type, function.location)
        parameters = ", ".join(
            f"{self._c_type(str(item.type_ref), item.location)} {item.name}"
            for item in function.parameters
        ) or "void"
        return f"{c_return} {function.name}({parameters})"

    def _function(self, function: FunctionDeclaration) -> str:
        self.current_function_name = function.name
        self.current_return_type = (
            "Int"
            if function.name == "main" and function.return_type is None
            else str(function.return_type) if function.return_type else "Void"
        )
        self.local_scopes = [
            {parameter.name: str(parameter.type_ref) for parameter in function.parameters}
        ]
        lines = [self._prototype(function) + " {"]
        lines.extend(self._block_lines(function.body, indent=1, create_scope=False))
        if function.name == "main" and not self._block_has_return(function.body):
            lines.append("    return 0;")
        lines.append("}")
        return "\n".join(lines)

    @staticmethod
    def _block_has_return(block: Block) -> bool:
        return any(isinstance(item, ReturnStatement) for item in block.statements)

    def _block_lines(
        self,
        block: Block,
        *,
        indent: int,
        create_scope: bool = True,
    ) -> list[str]:
        if create_scope:
            self.local_scopes.append({})
        try:
            lines: list[str] = []
            for statement in block.statements:
                lines.extend(self._statement(statement, indent))
            return lines
        finally:
            if create_scope:
                self.local_scopes.pop()

    def _statement(self, statement: object, indent: int) -> list[str]:
        prefix = "    " * indent
        if isinstance(statement, LetStatement):
            if isinstance(statement.value, OrReturnExpression):
                return self._or_return_let(statement, indent)
            inferred_type = self._infer_type(statement.value)
            if inferred_type is None:
                raise CodegenError(
                    "KS5002",
                    "Değişken tipi C backend tarafından çıkarılamadı.",
                    statement.location,
                )
            value_type = self._require_concrete_type(inferred_type, statement.location)
            self.local_scopes[-1][statement.name] = value_type
            return [
                f"{prefix}{self._c_type(value_type, statement.location)} {statement.name} = "
                f"{self._expression(statement.value, expected_type=value_type)};"
            ]

        if isinstance(statement, ReturnStatement):
            if statement.value is None:
                return [
                    f"{prefix}return 0;"
                    if self.current_function_name == "main"
                    else f"{prefix}return;"
                ]
            if isinstance(statement.value, OrReturnExpression):
                raise CodegenError(
                    "KS5001",
                    "'or return' doğrudan return ifadesinde henüz desteklenmiyor.",
                    statement.location,
                )
            expected = self.current_return_type or "Void"
            return [
                f"{prefix}return "
                f"{self._expression(statement.value, expected_type=expected)};"
            ]

        if isinstance(statement, ExpressionStatement):
            expression = statement.expression
            if (
                isinstance(expression, CallExpression)
                and isinstance(expression.callee, Identifier)
                and expression.callee.name in {"print", "println"}
            ):
                return [prefix + self._print_call(expression)]
            return [f"{prefix}{self._expression(expression)};"]

        if isinstance(statement, IfStatement):
            lines = [f"{prefix}if {self._condition(statement.condition)} {{"]
            lines.extend(self._block_lines(statement.then_branch, indent=indent + 1))
            if statement.else_branch is None:
                lines.append(f"{prefix}}}")
            else:
                lines.append(f"{prefix}}} else {{")
                lines.extend(
                    self._block_lines(statement.else_branch, indent=indent + 1)
                )
                lines.append(f"{prefix}}}")
            return lines

        if isinstance(statement, WhileStatement):
            lines = [f"{prefix}while {self._condition(statement.condition)} {{"]
            lines.extend(self._block_lines(statement.body, indent=indent + 1))
            lines.append(f"{prefix}}}")
            return lines

        if isinstance(statement, MatchStatement):
            return self._match_statement(statement, indent)

        raise CodegenError(
            "KS5001",
            f"C backend bu statement'i desteklemiyor: {type(statement).__name__}",
            statement.location,
        )

    def _condition(self, expression: Expression) -> str:
        rendered = self._expression(expression)
        if rendered.startswith("(") and rendered.endswith(")"):
            return rendered
        return f"({rendered})"

    def _match_statement(self, statement: MatchStatement, indent: int) -> list[str]:
        prefix = "    " * indent
        value_type = self._require_concrete_type(
            self._infer_type(statement.value), statement.location
        )
        generic = self._generic_parts(value_type)
        if not generic or generic[0] not in {"Option", "Result"}:
            raise CodegenError(
                "KS5001",
                "Native match yalnızca Option veya Result destekliyor.",
                statement.location,
            )
        if len(statement.arms) != 2:
            raise CodegenError(
                "KS5001",
                "Native match tam olarak iki doğrulanmış kol bekliyor.",
                statement.location,
            )
        c_type = self._c_type(value_type, statement.location)
        temp_name = self._next_temp("match")
        rendered = self._expression(statement.value, expected_type=value_type)
        lines = [f"{prefix}{c_type} {temp_name} = {rendered};"]
        first, second = statement.arms
        condition = self._match_condition(first.pattern.kind, temp_name)
        lines.append(f"{prefix}if ({condition}) {{")
        lines.extend(self._match_arm_lines(first, generic, temp_name, indent + 1))
        lines.append(f"{prefix}}} else {{")
        lines.extend(self._match_arm_lines(second, generic, temp_name, indent + 1))
        lines.append(f"{prefix}}}")
        return lines

    @staticmethod
    def _match_condition(kind: str, temp_name: str) -> str:
        if kind == "Some":
            return f"{temp_name}.is_some"
        if kind == "None":
            return f"!{temp_name}.is_some"
        if kind == "Ok":
            return f"{temp_name}.is_ok"
        if kind == "Err":
            return f"!{temp_name}.is_ok"
        raise AssertionError(kind)

    def _match_arm_lines(
        self,
        arm: object,
        generic: tuple[str, list[str]],
        temp_name: str,
        indent: int,
    ) -> list[str]:
        self.local_scopes.append({})
        try:
            lines: list[str] = []
            binding = arm.pattern.binding
            if binding is not None:
                _, arguments = generic
                if arm.pattern.kind == "Some":
                    payload_type = arguments[0]
                    payload = f"{temp_name}.value"
                elif arm.pattern.kind == "Ok":
                    payload_type = arguments[0]
                    payload = f"{temp_name}.value.ok"
                elif arm.pattern.kind == "Err":
                    payload_type = arguments[1]
                    payload = f"{temp_name}.value.err"
                else:
                    raise AssertionError(arm.pattern.kind)
                self.local_scopes[-1][binding] = payload_type
                prefix = "    " * indent
                lines.append(
                    f"{prefix}{self._c_type(payload_type, arm.pattern.location)} "
                    f"{binding} = {payload};"
                )
            lines.extend(
                self._block_lines(arm.body, indent=indent, create_scope=False)
            )
            return lines
        finally:
            self.local_scopes.pop()

    def _or_return_let(self, statement: LetStatement, indent: int) -> list[str]:
        expression = statement.value
        assert isinstance(expression, OrReturnExpression)
        prefix = "    " * indent
        source_type = self._require_concrete_type(
            self._infer_type(expression.value), expression.location
        )
        source_parts = self._generic_parts(source_type)
        if not source_parts or source_parts[0] != "Result" or len(source_parts[1]) != 2:
            raise CodegenError(
                "KS5001",
                "Native 'or return' şimdilik yalnızca Result<T, E> destekliyor.",
                expression.location,
            )
        success_type, source_error_type = source_parts[1]
        return_type = self._require_concrete_type(
            self.current_return_type, expression.location
        )
        return_parts = self._generic_parts(return_type)
        if not return_parts or return_parts[0] != "Result" or len(return_parts[1]) != 2:
            raise CodegenError(
                "KS5001",
                "'or return' kullanan fonksiyon Result<T, E> döndürmelidir.",
                expression.location,
            )
        return_error_type = return_parts[1][1]
        source_c = self._c_type(source_type, expression.location)
        return_c = self._c_type(return_type, expression.location)
        success_c = self._c_type(success_type, expression.location)
        temp_name = self._next_temp("result")
        rendered_value = self._expression(expression.value, expected_type=source_type)
        lines = [f"{prefix}{source_c} {temp_name} = {rendered_value};"]
        lines.append(f"{prefix}if (!{temp_name}.is_ok) {{")
        if expression.error is None:
            if source_error_type != return_error_type:
                raise CodegenError(
                    "KS5002",
                    f"'{source_error_type}' hatası '{return_error_type}' olarak aktarılamıyor.",
                    expression.location,
                )
            error_value = f"{temp_name}.value.err"
        else:
            error_value = self._expression(
                expression.error, expected_type=return_error_type
            )
        lines.append(f"{prefix}    return {return_c}_err({error_value});")
        lines.append(f"{prefix}}}")
        lines.append(f"{prefix}{success_c} {statement.name} = {temp_name}.value.ok;")
        self.local_scopes[-1][statement.name] = success_type
        return lines

    def _print_call(self, call: CallExpression) -> str:
        if len(call.arguments) != 1:
            raise CodegenError(
                "KS5001",
                "print/println tek argüman destekliyor.",
                call.location,
            )
        argument = call.arguments[0]
        type_name = self._infer_type(argument)
        formats = {
            "String": "%s",
            "Error": "%s",
            "Int": "%lld",
            "Float": "%g",
            "Bool": "%d",
        }
        if type_name not in formats:
            raise CodegenError(
                "KS5002",
                f"'{type_name}' tipi yazdırılamıyor.",
                call.location,
            )
        suffix = "\\n" if call.callee.name == "println" else ""
        rendered = self._expression(argument, expected_type=type_name)
        casts = {
            "Int": f"(long long)({rendered})",
            "Float": f"(double)({rendered})",
            "Bool": f"(int)({rendered})",
            "String": rendered,
            "Error": rendered,
        }
        return f'printf("{formats[type_name]}{suffix}", {casts[type_name]});'

    def _expression(
        self, expression: Expression, *, expected_type: str | None = None
    ) -> str:
        if isinstance(expression, Literal):
            if isinstance(expression.value, str):
                return '"' + self._escape_string(expression.value) + '"'
            if isinstance(expression.value, bool):
                return "true" if expression.value else "false"
            return repr(expression.value)

        if isinstance(expression, Identifier):
            if expression.name == "None":
                option_type = self._expect_generic_type(
                    expected_type, "Option", expression.location, "None"
                )
                return f"{self._c_type(option_type, expression.location)}_none()"
            return expression.name

        if isinstance(expression, UnaryExpression):
            return f"({expression.operator}{self._expression(expression.operand)})"

        if isinstance(expression, BinaryExpression):
            left = self._expression(expression.left)
            right = self._expression(expression.right)
            if expression.operator == "/":
                return f"(((double)({left})) / ((double)({right})))"
            return f"({left} {expression.operator} {right})"

        if isinstance(expression, AssignmentExpression):
            target_type = self._infer_type(expression.target)
            return (
                f"({self._expression(expression.target)} = "
                f"{self._expression(expression.value, expected_type=target_type)})"
            )

        if isinstance(expression, CallExpression):
            if isinstance(expression.callee, Identifier):
                name = expression.callee.name
                if name in {"print", "println"}:
                    raise CodegenError(
                        "KS5001",
                        "print çağrısı ifade içinde kullanılamaz.",
                        expression.location,
                    )
                if name == "Error":
                    self._require_call_arity(name, expression, 1)
                    return self._expression(
                        expression.arguments[0], expected_type="String"
                    )
                if name == "Some":
                    self._require_call_arity(name, expression, 1)
                    option_type = expected_type or self._infer_type(expression)
                    option_type = self._expect_generic_type(
                        option_type, "Option", expression.location, "Some"
                    )
                    inner_type = self._generic_parts(option_type)[1][0]
                    rendered = self._expression(
                        expression.arguments[0], expected_type=inner_type
                    )
                    return f"{self._c_type(option_type, expression.location)}_some({rendered})"
                if name in {"Ok", "Err"}:
                    self._require_call_arity(name, expression, 1)
                    result_type = expected_type or self._infer_type(expression)
                    result_type = self._expect_generic_type(
                        result_type, "Result", expression.location, name
                    )
                    ok_type, error_type = self._generic_parts(result_type)[1]
                    payload_type = ok_type if name == "Ok" else error_type
                    rendered = self._expression(
                        expression.arguments[0], expected_type=payload_type
                    )
                    suffix = "ok" if name == "Ok" else "err"
                    return f"{self._c_type(result_type, expression.location)}_{suffix}({rendered})"

                function = self.functions.get(name)
                expected_arguments = (
                    [str(item.type_ref) for item in function.parameters]
                    if function is not None
                    else [None] * len(expression.arguments)
                )
                arguments = ", ".join(
                    self._expression(item, expected_type=expected)
                    for item, expected in zip(
                        expression.arguments, expected_arguments, strict=True
                    )
                )
                return f"{name}({arguments})"

            arguments = ", ".join(
                self._expression(item) for item in expression.arguments
            )
            return f"{self._expression(expression.callee)}({arguments})"

        if isinstance(expression, OrReturnExpression):
            raise CodegenError(
                "KS5001",
                "'or return' yalnızca let bağlamında native olarak indirgenebilir.",
                expression.location,
            )

        if isinstance(expression, MemberExpression):
            raise CodegenError(
                "KS5001",
                "Capability ve üye erişimi native C backend kapsamına henüz alınmadı.",
                expression.location,
            )

        raise CodegenError(
            "KS5001",
            f"Bilinmeyen ifade: {type(expression).__name__}",
            expression.location,
        )

    def _infer_type(self, expression: Expression) -> str | None:
        if isinstance(expression, Literal):
            if isinstance(expression.value, bool):
                return "Bool"
            if isinstance(expression.value, str):
                return "String"
            if isinstance(expression.value, int):
                return "Int"
            if isinstance(expression.value, float):
                return "Float"

        if isinstance(expression, Identifier):
            if expression.name == "None":
                return "None"
            return self._lookup_local(expression.name)

        if isinstance(expression, UnaryExpression):
            return self._infer_type(expression.operand)

        if isinstance(expression, BinaryExpression):
            if expression.operator in {"==", "!=", "<", "<=", ">", ">="}:
                return "Bool"
            left = self._infer_type(expression.left)
            right = self._infer_type(expression.right)
            if expression.operator == "/" or "Float" in {left, right}:
                return "Float"
            if left == right == "Int":
                return "Int"
            return None

        if isinstance(expression, AssignmentExpression):
            return self._infer_type(expression.value)

        if isinstance(expression, OrReturnExpression):
            value_type = self._infer_type(expression.value)
            parts = self._generic_parts(value_type) if value_type else None
            if parts and parts[0] == "Result" and len(parts[1]) == 2:
                return parts[1][0]
            return None

        if isinstance(expression, CallExpression) and isinstance(
            expression.callee, Identifier
        ):
            name = expression.callee.name
            function = self.functions.get(name)
            if function:
                return str(function.return_type) if function.return_type else "Void"
            if name == "Error":
                return "Error"
            if name == "Some" and len(expression.arguments) == 1:
                inner = self._infer_type(expression.arguments[0]) or "Unknown"
                return f"Option<{inner}>"
            if name == "Ok" and len(expression.arguments) == 1:
                inner = self._infer_type(expression.arguments[0]) or "Unknown"
                return f"Result<{inner}, Unknown>"
            if name == "Err" and len(expression.arguments) == 1:
                inner = self._infer_type(expression.arguments[0]) or "Unknown"
                return f"Result<Unknown, {inner}>"
        return None

    def _lookup_local(self, name: str) -> str | None:
        for scope in reversed(self.local_scopes):
            if name in scope:
                return scope[name]
        return None

    def _c_type(self, type_name: str, location: SourceLocation) -> str:
        primitive = C_TYPES.get(type_name)
        if primitive is not None:
            return primitive
        parts = self._generic_parts(type_name)
        if parts is None:
            raise CodegenError(
                "KS5002",
                f"'{type_name}' tipi C backend tarafından desteklenmiyor.",
                location,
            )
        base, arguments = parts
        if base == "Option" and len(arguments) == 1:
            inner = self._require_storable(arguments[0], location)
            alias = self._mangle_type(type_name)
            if alias not in self.safe_type_definitions:
                inner_c = self._c_type(inner, location)
                self.safe_type_definitions[alias] = "\n".join(
                    (
                        "typedef struct {",
                        "    bool is_some;",
                        f"    {inner_c} value;",
                        f"}} {alias};",
                        "",
                        f"static inline {alias} {alias}_some({inner_c} value) {{",
                        f"    return ({alias}){{ .is_some = true, .value = value }};",
                        "}",
                        "",
                        f"static inline {alias} {alias}_none(void) {{",
                        f"    return ({alias}){{ .is_some = false }};",
                        "}",
                    )
                )
            return alias
        if base == "Result" and len(arguments) == 2:
            ok_type = self._require_storable(arguments[0], location)
            error_type = self._require_storable(arguments[1], location)
            alias = self._mangle_type(type_name)
            if alias not in self.safe_type_definitions:
                ok_c = self._c_type(ok_type, location)
                error_c = self._c_type(error_type, location)
                self.safe_type_definitions[alias] = "\n".join(
                    (
                        "typedef struct {",
                        "    bool is_ok;",
                        "    union {",
                        f"        {ok_c} ok;",
                        f"        {error_c} err;",
                        "    } value;",
                        f"}} {alias};",
                        "",
                        f"static inline {alias} {alias}_ok({ok_c} value) {{",
                        f"    return ({alias}){{ .is_ok = true, .value.ok = value }};",
                        "}",
                        "",
                        f"static inline {alias} {alias}_err({error_c} error) {{",
                        f"    return ({alias}){{ .is_ok = false, .value.err = error }};",
                        "}",
                    )
                )
            return alias
        raise CodegenError(
            "KS5002",
            f"'{type_name}' generic tipi C backend tarafından desteklenmiyor.",
            location,
        )

    @staticmethod
    def _require_storable(type_name: str, location: SourceLocation) -> str:
        if type_name in {"Void", "Unknown", "None"}:
            raise CodegenError(
                "KS5002",
                f"'{type_name}' safe-type alanında saklanamaz.",
                location,
            )
        return type_name

    @staticmethod
    def _require_concrete_type(
        type_name: str | None, location: SourceLocation
    ) -> str:
        if type_name is None or "Unknown" in type_name or type_name == "None":
            raise CodegenError(
                "KS5003",
                "Native safe type için somut tip bağlamı gerekiyor.",
                location,
            )
        return type_name

    def _expect_generic_type(
        self,
        type_name: str | None,
        expected_base: str,
        location: SourceLocation,
        constructor: str,
    ) -> str:
        concrete = self._require_concrete_type(type_name, location)
        parts = self._generic_parts(concrete)
        expected_arity = 1 if expected_base == "Option" else 2
        if not parts or parts[0] != expected_base or len(parts[1]) != expected_arity:
            raise CodegenError(
                "KS5003",
                f"'{constructor}' için {expected_base}<...> tip bağlamı gerekiyor.",
                location,
            )
        return concrete

    @staticmethod
    def _require_call_arity(
        name: str, expression: CallExpression, expected: int
    ) -> None:
        if len(expression.arguments) != expected:
            raise CodegenError(
                "KS5001",
                f"'{name}' {expected} argüman bekliyor.",
                expression.location,
            )

    def _next_temp(self, purpose: str) -> str:
        self.temp_counter += 1
        return f"__ks_{purpose}_{self.temp_counter}"

    @staticmethod
    def _mangle_type(type_name: str) -> str:
        normalized = re.sub(r"[^A-Za-z0-9]+", "_", type_name).strip("_").lower()
        return f"ks_{normalized}"

    @staticmethod
    def _generic_parts(type_name: str) -> tuple[str, list[str]] | None:
        if "<" not in type_name or not type_name.endswith(">"):
            return None
        base, raw = type_name.split("<", 1)
        raw = raw[:-1]
        arguments: list[str] = []
        start = 0
        depth = 0
        for index, char in enumerate(raw):
            depth += char == "<"
            depth -= char == ">"
            if char == "," and depth == 0:
                arguments.append(raw[start:index].strip())
                start = index + 1
        arguments.append(raw[start:].strip())
        return base, arguments

    @staticmethod
    def _escape_string(value: str) -> str:
        return (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
        )


def generate_c(program: Program) -> str:
    return CCodeGenerator(program).generate()
